### ISSUE TITLE
Updating artwork page for new inquireability

### ISSUE THREAD

**Issue by mzikherman** [artsy/microgravity#108]
Currently, sold work:

<img width="413" alt="screen shot 2017-01-31 at 12 59 27 pm" src="https://cloud.githubusercontent.com/assets/1457859/22477708/20dbb294-e7b5-11e6-8d8f-28643aff4379.png">

Not for sale:

<img width="419" alt="screen shot 2017-01-31 at 12 59 55 pm" src="https://cloud.githubusercontent.com/assets/1457859/22477724/3560837a-e7b5-11e6-8c55-d685a58ee4ea.png">

On hold:

<img width="418" alt="screen shot 2017-01-31 at 1 00 32 pm" src="https://cloud.githubusercontent.com/assets/1457859/22477745/466061ae-e7b5-11e6-8531-a0b15885c2ac.png">

Desired: https://cloud.githubusercontent.com/assets/1022172/22442271/c180c7d2-e708-11e6-851d-b29eb2e712f5.jpg

@tayapage6 @briansw similar to Force, can you comment on how the 'On hold' status should be displayed?

**Comment by mzikherman** [comment]
Use sample artworks referenced in https://github.com/artsy/force/issues/790 (one example of each).

**Comment by xtina-starr** [comment]
@briansw I have a couple of questions... I see the price label is not included in the spec. We added that a month or so for a specific reason (which I can't remember) and I wanted to check that it was intentional to not include it here. Also is the last instance of the artwork in the spec (where there is no price or sale message) the case for when a work is on hold?

**Comment by briansw** [comment]
@xtina-starr It's intentional. We're keeping the majority of the formatting, just dropping the price label as it's not necessary and clutters the layout a bit at mobile. 

I've updated the illustrations to include the on hold example. See the messages screen for which pre-filled messages to include for sold/not for sale/on hold. Let me know if you need anything clarified.

![artwork-nfs-hold-sold](https://cloud.githubusercontent.com/assets/1022172/22482251/220992b0-e7c6-11e6-93cd-e09bf0d62bc2.jpg)

**Comment by mzikherman** [comment]
@xtina-starr @briansw just for simplicity's sake, here are the 4 states and their appearance (on Microgravity and Force artwork pages):

**for sale**: this is unchanged, it still displays the price info/label/range, or 'Contact for Price'

**sold**: this now displays as 'sold' (no pricing info)

**not for sale**: this doesn't display anything (blank)

**on hold**: this displays as: "price, on hold" (if price available), otherwise just 'On hold'

For the 'on hold' state, I'd recommend a comma instead of a dash since the price could be a range (and contain a dash itself), and then lowercase 'on hold' (if no price available, 'On hold' with uppercase).

**Comment by xtina-starr** [comment]
@mzikherman this is helpful and pretty much inline with what I've started. Thx! I'm conditionally checking availability for `sold` or `on hold` and if neither of those are present defaulting to the `sale_message` to capture when a work is for sale but the price is hidden. One thing I had a question about was the contact gallery button. It pretty much seems as thought it's always available. Is this the case?

**Comment by mzikherman** [comment]
For the record- yep contact button always visible!
